# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b04d440c0d88d9a7d0a334b48d19e8d5f93f83041fddba55105f87d42b53906cf7aeb0adce213adb5e5bd27ee35f1f2f08c42fc23fdcda63932784de0284e7d

test:
  secret_key_base: d16a364eb80e884e8722a7ca48fb9dd80000cea834eff9f9cbd213f1fc388c55e03398464029e087204ddd1dfc601c7dd4cac0a8170baa267f6ba3ca6950e1f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
